#TODO: There's a lot of placeholders in here
version: "3.8"

services:
<<<<<<< HEAD
  # controller:
  #   build:
  #     context: ./controller
  #     dockerfile: Dockerfile
  #   environment:
  #     - AzureWebJobsStorage=''
  #     - DATABASE_URL=postgres://docker:docker@postgres:5432/docker
  #     - BUS_CONN=${BUS_CONN}
  #   platform: linux/amd64
  #   ports:
  #     - 8081:80
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     db-migrate:
  #       condition: service_completed_successfully
  db-seed:
    build:
      context: ./controller
      # dockerfile: Dockerfile
    entrypoint:
      [
        "sh",
        "-c",
        "psql postgres://docker:docker@postgres:5432/docker -f data_dump.sql",
      ]
    expose:
      - 7071
    depends_on:
      postgres:
        condition: service_healthy

=======
  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile
    environment:
      - AzureWebJobsStorage=<YOUR_STORAGE_CONNECTION_STRING>
      - DATABASE_URL=postgres://docker:docker@postgres:5432/docker
      - WEBSITE_CONTENTAZUREFILECONNECTIONSTRING=<YOUR_STORAGE_CONNECTION_STRING>
      - WEBSITE_CONTENTSHARE=<YOUR_STORAGE_CONTENT_SHARE_NAME>
    platform: linux/amd64
    ports:
      - 8081:80
    depends_on:
      postgres:
        condition: service_healthy
      db-migrate:
        condition: service_completed_successfully
>>>>>>> 90cec3e (add renderings table.  Move gateway to walangmeta. Rename some properties)
  db-migrate:
    build:
      context: ./controller
      dockerfile: Dockerfile
      # IF you want to run the functions in the container and migrate
    # entrypoint: ["sh", "-c", "pnpm run migrate && pnpm run start"]
    # IF you only want to migrate so hasura is up to date on migrations done locally
<<<<<<< HEAD
    entrypoint: pnpm run migrate
=======
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "psql postgres://docker:docker@postgres:5432/docker -f data_dump.sql && pnpm run migrate",
      ]
>>>>>>> 90cec3e (add renderings table.  Move gateway to walangmeta. Rename some properties)
    expose:
      - 7071
      - 3000
    # volumes:
    #   - ./data_dump.sql:/home/site/wwwroot/data_dump.sql
    ports:
      - 7071:7071
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://docker:docker@postgres:5432/docker
    depends_on:
      postgres:
        condition: service_healthy
      db-seed:
        condition: service_completed_successfully

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./data_only.sql:/docker-entrypoint-initdb.d/data_dump.sql
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 2s
  hasura:
    image: hasura/graphql-engine:v2.30.1.cli-migrations-v3
    volumes:
      - ./hasura/metadata:/hasura-metadata
    ports:
      - "8080:8080"
    depends_on:
      db-migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 2s
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://docker:docker@postgres:5432/docker
      PG_DATABASE_URL: postgres://docker:docker@postgres:5432/docker
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      # LANGNAMES_SYNC_WEBHOOK must be set on the container app, this is a placeholder, change if needed for local dev
      LANGNAMES_SYNC_WEBHOOK: "http://localhost:1234/prettypleasework"
  # langnames-generator:
  #   build:
  #     context: ./langnames-generator
  #     dockerfile: Dockerfile
  # langnames-server:
  #   build:
  #     context: ./langnames-server
  #     dockerfile: Dockerfile
  #   ports:
  #   - "8081:80"

volumes:
  pgdata:
